---
title: "R Data Analysis and Visualization Workshop"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### April 10 & 11, 2019


### [Pre-Workshop Setup](./00-Setup.html)  

## Workshop Lessons:  

### 1. [Spreadsheets](./01-Spreadsheets.html)  
*  Implement best practices in data table formatting  
*  Identify and address common formatting mistakes  

Download the data for the spreadsheet exercise [here](https://ndownloader.figshare.com/files/2252083).

### 2. [Why R (and R Studio)?](./02-Intro.html)
*  Describe the purpose of the RStudio Script, Console, Environment, and Plots panes.
*  Organize files and directories for a set of analyses as an R Project, and understand the purpose of the working directory.
*  Use the built-in RStudio help interface to search for more information on R functions.
*  Demonstrate how to provide sufficient information for troubleshooting with the R user community.  

Download the Day 1 Code Handout [here](./Day1_code_handout.R)

### 3. [Introduction to R](./03-R_Start.html)  
*  Define the following terms as they relate to R: object, assign, call, function, arguments, options.   
*  Assign values to objects in R.   
*  Learn how to name objects   
*  Use comments to inform script.   
*  Solve simple arithmetic operations in R.   
*  Call functions and use arguments to change their default options.   
*  Inspect the content of vectors and manipulate their content.   
*  Subset and extract values from vectors.   
*  Analyze vectors with missing data. 

### 4. [Starting with Data](./04-Data_Start.html)  
*  Describe what the `here` package does
*  Read in tibbles
*  Compare `read_csv` to `read.csv`
*  Extract values from tibbles
*  Perform basic operations on columns in a tibble.

### 5. [Manipulating Data with dplyr](./05-dplyr.html)  
*  Describe what the dplyr package in R is used for.  
*  Apply common dplyr functions to manipulate data in R.  
*  Employ the ‘pipe’ operator to link together a sequence of functions.  
*  Employ the ‘mutate’ function to apply other chosen functions to existing columns and create new columns of data.  
*  Employ the ‘split-apply-combine’ concept to split the data into groups, apply analysis to each group, and combine the results.  
*  Convert tibbles from long to wide and back again

### 6. [Introduction to Statistics](./06-introStats.html)
*  Describe the difference between populations and samples  
*  Distinguish between data that follows a normal distribution and data that deviates in modality, skew, or kurtosis  
*  Define the difference between null and alternate hypothesis  
*  Define type I and type II error  
*  Describe the relationship between alpha, beta and power  

### 7. [Exploratory Data Analysis](./07-EDA.html)
* Produce histograms, barplot, boxplots, violin plots and scatterplots plot using ggplot.
* Describe what faceting is and apply faceting in ggplot.
* Modify the aesthetics of an existing ggplot plot (including axis labels and color).
* Build complex and customized plots from data in a data frame.
* Be wowed by the power of R and compelled to keep using it after this workshop

Download the Day 2 Code Handout Skeleton [here](./Day2_code_handout_skeleton.R)
Download the Day 2 Code Handout [here](./Day2_code_handout.R)

### [Post-Workshop Survey (please do this before you leave the room)](https://www.microstatslab.ca/mbio7040-post-workshop-survey.html) 

### So you want to learn more?
* [R for Data Science book](https://r4ds.had.co.nz/)  

* [More R in a course: UBC Stats 545](https://stat545.com/)  

* [Modern Dive data science statistics textbook](https://moderndive.com/)  

* [More biostats in a course: UBC Zoology 501](https://www.zoology.ubc.ca/~schluter/R/)  

### RMD files
Markdown files are available on [github](https://github.com/acgerstein/MBIO7040-UManitoba)
